repos:
# - repo: local
#   hooks:
#   - id: ruff-check
#     name: ruff check
#     entry: uv run ruff check --fix
#     language: system
#     types: [python]
#     pass_filenames: false

#   - id: ruff-format
#     name: ruff format
#     entry: uv run ruff format
#     language: system
#     types: [python]
#     pass_filenames: false

#   # # Too long: Run tests with pytest
#   # - id: run-pytest
#   #   name: pytest
#   #   entry: uv run pytest -n auto submitthem --cov=submitthem
#   #   language: system
#   #   types: [python]
#   #   pass_filenames: false

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.14.9
  hooks:
  - id: ruff-check
    args: [--fix]
  - id: ruff-format

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-added-large-files
    args: ['--maxkb=1000']
  - id: check-merge-conflict
